services:
  eureka-server:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: eureka-server-dev
    network_mode: host
    volumes:
      - ./codigo-eureka:/app
    working_dir: /app
    command: tail -f /dev/null
    restart: always

